GET http://localhost:3000/

###

GET http://localhost:3000/footballers

###

GET http://localhost:3000/footballers/properties/:id

###

GET http://localhost:3000/footballers/properties/:name

###

GET http://localhost:3000/footballers/properties/age

###

GET http://localhost:3000/footballers/properties/league

###

GET http://localhost:3000/footballers/properties/team

###

GET http://localhost:3000/footballers/properties/nationality

###
GET http://localhost:3000/footballers/properties/career

###

GET http://localhost:3000/footballers/properties/foot

###

GET http://localhost:3000/footballers/properties/position

###

POST http://localhost:3000/footballers/create
Content-Type: application/json

{"name": "Federico Gatti", "age": }