GET http://localhost:3000/

###

GET http://localhost:3000/footballers

###

GET http://localhost:3000/footballers/properties/name/CristianoRonaldo

###

GET http://localhost:3000/footballers/properties/Cristiano

###

GET http://localhost:3000/footballers/properties/age/53

###

GET http://localhost:3000/footballers/properties/leagues/Serie%20A

###

GET http://localhost:3000/footballers/properties/team

###

GET http://localhost:3000/footballers/properties/nationality

###
GET http://localhost:3000/footballers/properties/career

###

GET http://localhost:3000/footballers/properties/foot

###

GET http://localhost:3000/footballers/properties/position

###

POST http://localhost:3000/footballers
Content-Type: application/json

{"name": "Federico Gatti", "age": 25, "leagues": ["Serie A"], "teams": ["Juventus"], "nationality": "Italy", "career": 1, "foot": "Right", "position": "DEF"}

###

DELETE http://localhost:3000/footballers/10
